#!/bin/sh
# shellcheck disable=SC2016  # harness text may hold a literal $ (Codex skill names)
# LapisLazuli installer for macOS and Linux (POSIX sh).
# Generated by tools/build/installers.py from install/harnesses.yaml; do not edit.
# Every harness command is an argv list from that file, run as quoted words; nothing is eval'd.
set -u

LL_VERSION='0.2.0'
LL_REPO='lapis-labs/lapis-lazuli'
LL_REF='release'
LL_RAW='https://raw.githubusercontent.com/lapis-labs/lapis-lazuli/release'
LL_DOCS='https://github.com/lapis-labs/lapis-lazuli/blob/release/INSTALLATION.md'
LL_ALL_PLUGINS='lapis ultramarine lazuli'
LL_ALL_HARNESSES='claude-code codex oh-my-pi pi hermes antigravity other'
LL_EXPERIMENTAL='pi hermes antigravity'
LL_CLI_NAME='CLI (lapis-design, lapis-design-hook, lazuli)'
LL_CLI_NEEDS='uv or pipx'
LL_NL='
'
LL_MODE=install
LL_DRY=0
LL_YES=0
LL_WANT_H=
LL_WANT_P=
LL_PLUGINS=
LL_SKILLS=
LL_TARGETS=
LL_H=
LL_MANUAL=0
LL_sha=
LL_SHA_STATE=
LL_checkout=
LL_CHECKOUT_STATE=
LL_CHECKOUT_DIR=
LL_TOOL=
LL_TODO=
LL_CHECKS=
LL_NOTES=
LL_CHANGES=
LL_FAILED=
LL_SNIPPETS=
LL_WHY=
LL_LOOK=
LL_ANCHOR=
LL_AGENTS_other=

say() { printf '%s\n' "$*"; }
err() { printf '%s\n' "$*" >&2; }

usage() {
  cat <<'EOF'
Usage: install.sh [options]

Installs the LapisLazuli CLI (lapis-design, lapis-design-hook, lazuli) with uv or pipx and adds the plugins to every
harness it finds. Guide: https://github.com/lapis-labs/lapis-lazuli/blob/release/INSTALLATION.md

Options:
  --dry-run        print every command it would run; change nothing
  --harness ID     only this harness (repeatable): claude-code, codex, oh-my-pi, pi, hermes, antigravity, other
                   experimental, so installed only when named here: pi, hermes, antigravity
  --plugin NAME    only this plugin (repeatable; default: all): lapis, ultramarine, lazuli
  --update         run the update steps and reinstall the CLI from release
  --uninstall      run the removal steps; a catalog goes only with every plugin, and
                   the CLI only with every plugin from every harness
  --yes, -y        answer yes to every question
  --help, -h       show this help
EOF
}

usage_error() {
  err "install.sh: $1"
  usage >&2
  exit 2
}

has_cmd() { command -v "$1" >/dev/null 2>&1; }
has_dir() { [ -d "$1" ]; }

# in_list WORD LIST: WORD (a slug) is one of the space-separated LIST.
in_list() {
  case $1 in '' | *[!a-z0-9-]*) return 1 ;; esac
  case " $2 " in *" $1 "*) return 0 ;; esac
  return 1
}

# skips_experimental ID: installing without --harness leaves out an experimental harness that was only found.
skips_experimental() {
  [ "$LL_MODE" = install ] && [ -z "$LL_WANT_H" ] && in_list "$1" "$LL_EXPERIMENTAL"
}

selected() { in_list "$1" "$LL_PLUGINS"; }
all_plugins() { [ "$LL_PLUGINS" = "$LL_ALL_PLUGINS" ]; }

skills_of() {
  case $1 in
  lapis) printf '%s' 'lapis lps-brief lps-ux lps-copy lps-system' ;;
  ultramarine) printf '%s' 'ultramarine ulm-maintain ulm-release' ;;
  lazuli) printf '%s' 'lazuli lzl-fonts lzl-color lzl-research' ;;
  esac
}

# sq WORD: WORD quoted for sh when it needs quotes.
sq() {
  case $1 in
    '') printf "''" ;;
    *[!A-Za-z0-9_./:@+,-]*)
      LL_s=$1
      LL_q=
      while :; do
        case $LL_s in
          *"'"*)
            LL_q=$LL_q${LL_s%%"'"*}"'\\''"
            LL_s=${LL_s#*"'"}
            ;;
          *)
            LL_q=$LL_q$LL_s
            break
            ;;
        esac
      done
      printf "'%s'" "$LL_q"
      ;;
    *) printf '%s' "$1" ;;
  esac
}

qargv() {
  LL_qa=
  for LL_a in "$@"; do LL_qa="$LL_qa${LL_qa:+ }$(sq "$LL_a")"; done
  printf '%s' "$LL_qa"
}

# Lists printed at the end.
todo() { LL_TODO="$LL_TODO- $1$LL_NL"; }
changed() { LL_CHANGES="$LL_CHANGES- $1$LL_NL"; }
failed() {
  LL_FAILED="$LL_FAILED- $1$LL_NL"
  say "  failed: $1"
}
note() {
  [ -n "$1" ] || return 0
  case "$LL_NL$LL_NOTES" in *"$LL_NL- $LL_H: $1$LL_NL"*) return 0 ;; esac
  LL_NOTES="$LL_NOTES- $LL_H: $1$LL_NL"
}
note_whole() {
  all_plugins || say "  note: $LL_H takes every plugin at once; --plugin does not narrow it"
}
check_cmd() { LL_CHECKS="$LL_CHECKS- $LL_H: $(qargv "$@")$LL_NL"; }
check_expect() { LL_CHECKS="$LL_CHECKS    expect: $1$LL_NL"; }
check_manual() { LL_CHECKS="$LL_CHECKS- $LL_H: $1$LL_NL"; }
snippet() {
  case "$LL_NL$LL_SNIPPETS$LL_NL" in *"$LL_NL$1$LL_NL"*) return 0 ;; esac
  LL_SNIPPETS="${LL_SNIPPETS:+$LL_SNIPPETS$LL_NL}$1"
}

print_block() {
  [ -n "$2" ] || return 0
  say ""
  say "$1"
  printf '%s' "$2" | while IFS= read -r LL_l; do say "$3$LL_l"; done
}

# ask QUESTION: yes only for y or yes (--yes answers for the user).
ask() {
  if [ "$LL_YES" = 1 ]; then
    say "  $1 [y/N] y (--yes)"
    return 0
  fi
  printf '  %s [y/N] ' "$1"
  LL_ans=
  IFS= read -r LL_ans || LL_ans=
  [ -t 0 ] || say "$LL_ans"
  case $LL_ans in [yY] | [yY][eE][sS]) return 0 ;; esac
  return 1
}

fetch() {
  if has_cmd curl; then
    command curl -fsSL -o "$2" "$1"
  elif has_cmd wget; then
    command wget -q -O "$2" "$1"
  else
    say "  neither curl nor wget is on PATH"
    return 1
  fi
}

# begin NAME [COMMAND...]: start a section; when a command is missing, its steps become a to-do list.
begin() {
  LL_H=$1
  shift
  LL_MANUAL=0
  LL_missing=
  for LL_c in "$@"; do
    has_cmd "$LL_c" || LL_missing="${LL_missing:+$LL_missing, }$LL_c"
  done
  say ""
  say "== $LL_H"
  if [ -n "$LL_missing" ]; then
    LL_MANUAL=1
    say "  not on PATH: $LL_missing; the steps are listed under 'To do by hand'"
  fi
}

skip_all() { say "  not now (only when every plugin is removed): $1"; }

# step_run ASK NOTE ARGV...: run one command; ASK 1 asks first.
step_run() {
  LL_ask=$1
  LL_note=$2
  shift 2
  LL_line=$(qargv "$@")
  note "$LL_note"
  if [ "$LL_MANUAL" = 1 ]; then
    todo "$LL_H: $LL_line"
    return 0
  fi
  if [ "$LL_DRY" = 1 ]; then
    if [ "$LL_ask" = 1 ] && [ "$LL_YES" = 0 ]; then
      say "  would ask, then run: $LL_line"
    else
      say "  would run: $LL_line"
    fi
    return 0
  fi
  if [ "$LL_ask" = 1 ]; then
    [ -z "$LL_note" ] || say "  note: $LL_note"
    if ! ask "Run $LL_line ?"; then
      say "  skipped: $LL_line"
      todo "$LL_H (you declined): $LL_line"
      return 0
    fi
  fi
  say "  run: $LL_line"
  command "$@"
  LL_st=$?
  if [ "$LL_st" -eq 0 ]; then
    changed "$LL_H: ran $LL_line"
  else
    failed "$LL_H: $LL_line (exit $LL_st)"
  fi
  return 0
}

# step_copy ASK NOTE SOURCE DEST: copy SOURCE (a repository path at the release ref) to DEST.
step_copy() {
  LL_ask=$1
  LL_note=$2
  LL_url="$LL_RAW/$3"
  LL_dest=$4
  note "$LL_note"
  if [ "$LL_MANUAL" = 1 ]; then
    todo "$LL_H: copy $LL_url to $LL_dest"
    return 0
  fi
  if [ "$LL_DRY" = 1 ]; then
    if [ "$LL_ask" = 1 ] && [ "$LL_YES" = 0 ]; then
      say "  would ask, then copy: $LL_url -> $LL_dest"
    else
      say "  would copy: $LL_url -> $LL_dest"
    fi
    return 0
  fi
  if ! LL_tmp=$(mktemp "${TMPDIR:-/tmp}/lapis-lazuli.XXXXXX"); then
    failed "$LL_H: could not create a temporary file"
    return 0
  fi
  say "  download: $LL_url"
  if ! fetch "$LL_url" "$LL_tmp"; then
    rm -f "$LL_tmp"
    failed "$LL_H: could not download $LL_url"
    return 0
  fi
  if [ -f "$LL_dest" ] && cmp -s "$LL_tmp" "$LL_dest"; then
    rm -f "$LL_tmp"
    say "  unchanged: $LL_dest"
    return 0
  fi
  if [ "$LL_ask" = 1 ] && ! ask "Copy ${3##*/} to $LL_dest ?"; then
    rm -f "$LL_tmp"
    say "  skipped: copy to $LL_dest"
    todo "$LL_H (you declined): copy $LL_url to $LL_dest"
    return 0
  fi
  if mkdir -p "${LL_dest%/*}" && cat "$LL_tmp" >"$LL_dest"; then
    say "  copied: $LL_dest"
    changed "$LL_H: copied $LL_url to $LL_dest"
  else
    failed "$LL_H: could not write $LL_dest"
  fi
  rm -f "$LL_tmp"
}

# step_remove ASK NOTE PATH: remove one file, or one empty folder when PATH ends in /.
step_remove() {
  LL_ask=$1
  LL_note=$2
  LL_dest=$3
  LL_action="remove $LL_dest"
  case $LL_dest in */) LL_action="remove folder if empty: $LL_dest" ;; esac
  note "$LL_note"
  if [ "$LL_MANUAL" = 1 ]; then
    todo "$LL_H: $LL_action"
    return 0
  fi
  case $LL_dest in
    */)
      LL_folder=${LL_dest%/}
      LL_reason=
      if [ -L "$LL_folder" ]; then
        LL_reason='symbolic link'
      elif [ -e "$LL_folder" ] && [ ! -d "$LL_folder" ]; then
        LL_reason='not a folder'
      elif [ -d "$LL_folder" ] && { [ ! -r "$LL_folder" ] || [ ! -x "$LL_folder" ]; }; then
        LL_reason=unreadable
      fi
      if [ -n "$LL_reason" ]; then
        say "  kept ($LL_reason): $LL_dest"
        todo "$LL_H: $LL_action"
        return 0
      fi
      ;;
  esac
  if [ ! -e "$LL_dest" ]; then
    say "  already absent: $LL_dest"
    return 0
  fi
  if [ "$LL_DRY" = 1 ]; then
    if [ "$LL_ask" = 1 ] && [ "$LL_YES" = 0 ]; then
      say "  would ask, then $LL_action"
    else
      say "  would $LL_action"
    fi
    return 0
  fi
  if [ "$LL_ask" = 1 ] && ! ask "Remove $LL_dest ?"; then
    say "  skipped: $LL_action"
    todo "$LL_H (you declined): $LL_action"
    return 0
  fi
  case $LL_dest in
    */)
      for LL_entry in "$LL_dest"* "$LL_dest".*; do
        case ${LL_entry##*/} in .|..) continue ;; esac
        if [ -e "$LL_entry" ] || [ -L "$LL_entry" ]; then
          say "  kept (not empty): $LL_dest"
          todo "$LL_H: $LL_action"
          return 0
        fi
      done
      if rmdir "$LL_dest" 2>/dev/null; then
        say "  removed empty folder: $LL_dest"
        changed "$LL_H: removed empty folder $LL_dest"
      else
        say "  kept (could not remove empty folder): $LL_dest"
        todo "$LL_H: $LL_action"
      fi
      ;;
    *)
      if rm -f "$LL_dest"; then
        say "  removed: $LL_dest"
        changed "$LL_H: removed $LL_dest"
      else
        failed "$LL_H: could not remove $LL_dest"
      fi
      ;;
  esac
}

step_manual() { todo "$LL_H: $1"; }

# need_sha: set LL_sha to the full commit the release ref points to.
need_sha() {
  if [ "$LL_DRY" = 1 ]; then
    [ -n "$LL_sha" ] || say "  would run: git ls-remote https://github.com/$LL_REPO refs/heads/$LL_REF"
    LL_sha='<commit>'
    return 0
  fi
  [ "$LL_SHA_STATE" != ok ] || return 0
  if [ -z "$LL_SHA_STATE" ]; then
    LL_SHA_STATE=failed
    if has_cmd git; then
      say "  run: git ls-remote https://github.com/$LL_REPO refs/heads/$LL_REF"
      LL_out=$(GIT_TERMINAL_PROMPT=0 command git ls-remote "https://github.com/$LL_REPO" "refs/heads/$LL_REF") || LL_out=
      LL_first=${LL_out%%[!0-9a-f]*}
      if [ ${#LL_first} -eq 40 ]; then
        LL_sha=$LL_first
        LL_SHA_STATE=ok
        say "  commit: $LL_sha"
        return 0
      fi
    fi
    say "  could not read the commit $LL_REF points to (git ls-remote https://github.com/$LL_REPO refs/heads/$LL_REF)"
  fi
  if [ "$LL_MANUAL" = 1 ]; then
    LL_sha='<commit>'
    return 0
  fi
  failed "$LL_H: skipped a step that needs the commit of $LL_REF"
  return 1
}

# cleanup: delete the temporary clone need_checkout made. It only runs from the EXIT trap, which shellcheck does not follow.
# shellcheck disable=SC2317
cleanup() {
  [ -z "$LL_CHECKOUT_DIR" ] || rm -rf "$LL_CHECKOUT_DIR"
}

# need_checkout: set LL_checkout to a shallow clone of the release ref in a temporary folder (deleted when the
# script ends), for a harness that installs from a local folder.
need_checkout() {
  if [ "$LL_DRY" = 1 ]; then
    [ -n "$LL_checkout" ] || say "  would run: git clone --depth 1 --branch $LL_REF https://github.com/$LL_REPO <checkout>"
    LL_checkout='<checkout>'
    return 0
  fi
  if [ "$LL_MANUAL" = 1 ]; then
    LL_checkout='<checkout>'
    return 0
  fi
  [ "$LL_CHECKOUT_STATE" != ok ] || return 0
  if [ -z "$LL_CHECKOUT_STATE" ]; then
    LL_CHECKOUT_STATE=failed
    if has_cmd git && LL_dir=$(mktemp -d "${TMPDIR:-/tmp}/lapis-lazuli-checkout.XXXXXX"); then
      LL_CHECKOUT_DIR=$LL_dir
      say "  run: git clone --depth 1 --branch $LL_REF https://github.com/$LL_REPO $LL_dir"
      if GIT_TERMINAL_PROMPT=0 command git clone --depth 1 --branch "$LL_REF" "https://github.com/$LL_REPO" "$LL_dir"; then
        LL_checkout=$LL_dir
        LL_CHECKOUT_STATE=ok
        return 0
      fi
    fi
    say "  could not clone $LL_REF (git clone --depth 1 --branch $LL_REF https://github.com/$LL_REPO)"
  fi
  failed "$LL_H: skipped a step that needs a clone of $LL_REF"
  return 1
}

# verify_cmd EXPECT ARGV...: one CLI check.
verify_cmd() {
  LL_exp=$1
  shift
  LL_line=$(qargv "$@")
  if [ "$LL_DRY" = 1 ]; then
    say "  would check: $LL_line"
    say "    expect: $LL_exp"
    return 0
  fi
  if ! has_cmd "$1"; then
    failed "CLI: $1 is not on PATH; open a new terminal$(path_hint)"
    return 0
  fi
  say "  check: $LL_line"
  say "    expect: $LL_exp"
  command "$@"
  LL_st=$?
  [ "$LL_st" -eq 0 ] || failed "CLI: $LL_line (exit $LL_st)"
}

show_snippets() {
  [ -n "$LL_SNIPPETS" ] || return 0
  printf '%s\n' "$LL_SNIPPETS" | while IFS= read -r LL_s; do
    LL_url="$LL_RAW/$LL_s"
    say ""
    say "== Instructions snippet: $LL_s"
    say "  Add it to your agent's instructions file yourself; this script never edits one."
    if [ "$LL_DRY" = 1 ]; then
      say "  would show: $LL_url"
      continue
    fi
    LL_tmp=$(mktemp "${TMPDIR:-/tmp}/lapis-lazuli.XXXXXX") || continue
    if fetch "$LL_url" "$LL_tmp"; then
      say "----- $LL_s -----"
      cat "$LL_tmp"
      say "----- end of $LL_s -----"
    else
      say "  could not download it; open $LL_url"
    fi
    rm -f "$LL_tmp"
  done
}

# The CLI: the first tool on PATH wins.
cli_tool() {
  case $1 in
  install) if has_cmd uv; then printf '%s' uv; return 0; fi; if has_cmd pipx; then printf '%s' pipx; return 0; fi ;;
  uninstall) if has_cmd uv; then printf '%s' uv; return 0; fi; if has_cmd pipx; then printf '%s' pipx; return 0; fi ;;
  esac
  return 1
}

cli_steps() {
  case $1:$2 in
  install:uv)
    step_run 0 '' uv tool install --force git+https://github.com/lapis-labs/lapis-lazuli@release
    ;;
  install:pipx)
    step_run 0 '' pipx install --force git+https://github.com/lapis-labs/lapis-lazuli@release
    ;;
  uninstall:uv)
    step_run 0 '' uv tool uninstall lapis-design
    ;;
  uninstall:pipx)
    step_run 0 '' pipx uninstall lapis-design
    ;;
  esac
}

cli_verify() {
  verify_cmd 'prints the version of release' lapis-design --version
  verify_cmd 'exit code 0' lazuli doctor
}

path_hint() {
  case $LL_TOOL in
  uv) printf '%s' '; or run: uv tool update-shell' ;;
  pipx) printf '%s' '; or run: pipx ensurepath' ;;
  esac
}

# Claude Code
h_claude_code() {
  case $1 in
  name) LL_H='Claude Code' ;;
  detect)
    LL_WHY=
    if has_cmd claude; then LL_WHY="${LL_WHY:+$LL_WHY, }command claude"; fi
    if has_dir "$HOME"/.claude; then LL_WHY="${LL_WHY:+$LL_WHY, }folder ~/.claude"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='command claude or folder ~/.claude' LL_ANCHOR='#claude-code' ;;
  install)
    begin 'Claude Code' claude
    step_run 0 '' claude plugin marketplace add lapis-labs/lapis-lazuli@release
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' claude plugin install "$LL_plugin"@lapis-lazuli -s user
    done
    ;;
  update)
    begin 'Claude Code' claude
    step_run 0 '' claude plugin marketplace update lapis-lazuli
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 'the new version loads in the next session or after /reload-plugins' claude plugin update "$LL_plugin"@lapis-lazuli
    done
    ;;
  uninstall)
    begin 'Claude Code' claude
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' claude plugin uninstall "$LL_plugin"@lapis-lazuli -s user
    done
    if all_plugins; then
      step_run 0 'removing the catalog uninstalls every plugin installed from it' claude plugin marketplace remove lapis-lazuli
    else
      skip_all 'claude plugin marketplace remove lapis-lazuli'
    fi
    ;;
  verify)
    check_cmd claude plugin list --json
    for LL_plugin in $LL_PLUGINS; do
      check_expect 'an enabled entry '"$LL_plugin"'@lapis-lazuli with no errors'
    done
    check_manual 'In a session, run /lapis:lapis and check that the skill loads'
    : ;;
  esac
}

# OpenAI Codex CLI
h_codex() {
  case $1 in
  name) LL_H='OpenAI Codex CLI' ;;
  detect)
    LL_WHY=
    if has_cmd codex; then LL_WHY="${LL_WHY:+$LL_WHY, }command codex"; fi
    if has_dir "$HOME"/.codex; then LL_WHY="${LL_WHY:+$LL_WHY, }folder ~/.codex"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='command codex or folder ~/.codex' LL_ANCHOR='#openai-codex-cli' ;;
  install)
    begin 'OpenAI Codex CLI' codex
    note 'needs version 0.153.0 or later'
    step_run 0 '' codex plugin marketplace add lapis-labs/lapis-lazuli --ref release
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' codex plugin add "$LL_plugin"@lapis-lazuli
    done
    if selected ultramarine; then
      step_copy 1 '' dist/codex/agents/ulm-critic.toml "$HOME"/.codex/agents/ulm-critic.toml
    fi
    step_manual 'Open /hooks in Codex and trust the lazuli session-start hook and the lapis stop and pre-write hooks; none of them runs until trusted'
    ;;
  update)
    begin 'OpenAI Codex CLI' codex
    note 'needs version 0.153.0 or later'
    step_run 0 'there is no per-plugin update; new skills appear in the next session' codex plugin marketplace upgrade lapis-lazuli
    if selected ultramarine; then
      step_copy 1 '' dist/codex/agents/ulm-critic.toml "$HOME"/.codex/agents/ulm-critic.toml
    fi
    ;;
  uninstall)
    begin 'OpenAI Codex CLI' codex
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' codex plugin remove "$LL_plugin"@lapis-lazuli
    done
    if all_plugins; then
      step_run 0 '' codex plugin marketplace remove lapis-lazuli
    else
      skip_all 'codex plugin marketplace remove lapis-lazuli'
    fi
    if all_plugins; then
      step_remove 0 '' "$HOME"/.codex/plugins/cache/lapis-lazuli/
    else
      skip_all 'remove folder if empty: ~/.codex/plugins/cache/lapis-lazuli/'
    fi
    if selected ultramarine; then
      step_remove 1 '' "$HOME"/.codex/agents/ulm-critic.toml
    fi
    ;;
  verify)
    check_cmd codex plugin list --json
    for LL_plugin in $LL_PLUGINS; do
      check_expect "$LL_plugin"'@lapis-lazuli installed and enabled'
    done
    for LL_plugin in $(pick 'ultramarine'); do
      check_manual 'For '"$LL_plugin"', check that ~/.codex/agents/ulm-critic.toml exists and matches dist/codex/agents/ulm-critic.toml from lapis-labs/lapis-lazuli at release; a marketplace upgrade alone does not copy the critic file'
    done
    check_manual 'In a new session, type $lapis:lps-ux and check that the skill is offered'
    : ;;
  esac
}

# Oh-My-Pi
h_oh_my_pi() {
  case $1 in
  name) LL_H='Oh-My-Pi' ;;
  detect)
    LL_WHY=
    if has_cmd omp; then LL_WHY="${LL_WHY:+$LL_WHY, }command omp"; fi
    if has_dir "$HOME"/.omp; then LL_WHY="${LL_WHY:+$LL_WHY, }folder ~/.omp"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='command omp or folder ~/.omp' LL_ANCHOR='#oh-my-pi' ;;
  install)
    begin 'Oh-My-Pi' omp
    step_run 0 '' omp plugin marketplace add lapis-labs/lapis-lazuli
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' omp plugin install --scope user "$LL_plugin"@lapis-lazuli
    done
    step_manual 'Restart omp so the session-start and exit-gate extensions load; /reload-plugins refreshes skills and MCP only'
    ;;
  update)
    begin 'Oh-My-Pi' omp
    step_run 0 '' omp plugin marketplace update lapis-lazuli
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' omp plugin upgrade --scope user "$LL_plugin"@lapis-lazuli
    done
    ;;
  uninstall)
    begin 'Oh-My-Pi' omp
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' omp plugin uninstall --scope user "$LL_plugin"@lapis-lazuli
    done
    if all_plugins; then
      step_run 0 '' omp plugin marketplace remove lapis-lazuli
    else
      skip_all 'omp plugin marketplace remove lapis-lazuli'
    fi
    ;;
  verify)
    check_cmd omp plugin list
    for LL_plugin in $LL_PLUGINS; do
      check_expect "$LL_plugin"'@lapis-lazuli listed and enabled'
    done
    check_manual 'In a session, run /skill:lps-ux'
    : ;;
  esac
}

# pi
h_pi() {
  case $1 in
  name) LL_H='pi' ;;
  detect)
    LL_WHY=
    if has_cmd pi; then LL_WHY="${LL_WHY:+$LL_WHY, }command pi"; fi
    if has_dir "$HOME"/.pi/agent; then LL_WHY="${LL_WHY:+$LL_WHY, }folder ~/.pi/agent"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='command pi or folder ~/.pi/agent' LL_ANCHOR='#pi' ;;
  install)
    begin 'pi' pi
    note_whole
    step_run 0 '' pi install git:github.com/lapis-labs/lapis-lazuli@release
    ;;
  update)
    begin 'pi' pi
    note_whole
    step_run 0 'pi keys git packages by repository without the ref, so installing again replaces the older install' pi install git:github.com/lapis-labs/lapis-lazuli@release
    ;;
  uninstall)
    begin 'pi' pi
    if all_plugins; then
      step_run 0 'one package carries every plugin'\''s skills, so it goes only when every plugin is removed' pi remove git:github.com/lapis-labs/lapis-lazuli
    else
      skip_all 'pi remove git:github.com/lapis-labs/lapis-lazuli'
    fi
    ;;
  verify)
    check_cmd pi list
    check_expect 'the lapis-labs/lapis-lazuli package is listed'
    check_manual 'In a session, run /skill:lps-ux'
    : ;;
  esac
}

# Hermes Agent
h_hermes() {
  case $1 in
  name) LL_H='Hermes Agent' ;;
  detect)
    LL_WHY=
    if has_cmd hermes; then LL_WHY="${LL_WHY:+$LL_WHY, }command hermes"; fi
    if has_dir "$HOME"/.hermes; then LL_WHY="${LL_WHY:+$LL_WHY, }folder ~/.hermes"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='command hermes or folder ~/.hermes' LL_ANCHOR='#hermes-agent' ;;
  install)
    begin 'Hermes Agent' hermes
    for LL_skill in $LL_SKILLS; do
      step_run 0 '' hermes skills install lapis-labs/lapis-lazuli/dist/skills/"$LL_skill" --yes
    done
    if need_sha; then
      step_run 1 'plugins are disabled by default; --enable turns this one on. --ref takes only a full commit' hermes plugins install lapis-labs/lapis-lazuli/plugins/hermes/lapis-lazuli --ref "$LL_sha" --enable
    fi
    step_run 0 '' hermes mcp add lapis-lazuli --command lapis-design --args mcp
    ;;
  update)
    begin 'Hermes Agent' hermes
    note_whole
    step_run 0 '' hermes skills update
    if need_sha; then
      step_run 1 'update refuses to move a pinned plugin; reinstall at the new commit' hermes plugins install lapis-labs/lapis-lazuli/plugins/hermes/lapis-lazuli --ref "$LL_sha" --enable --force
    fi
    ;;
  uninstall)
    begin 'Hermes Agent' hermes
    for LL_skill in $LL_SKILLS; do
      step_run 0 '' hermes skills uninstall "$LL_skill"
    done
    if all_plugins; then
      step_run 0 'the one Hermes plugin serves every skill'\''s session summary' hermes plugins remove lapis-lazuli
    else
      skip_all 'hermes plugins remove lapis-lazuli'
    fi
    if all_plugins; then
      step_run 0 '' hermes mcp remove lapis-lazuli
    else
      skip_all 'hermes mcp remove lapis-lazuli'
    fi
    ;;
  verify)
    check_cmd hermes skills list
    check_expect 'every skill of the selected plugins is listed'
    check_cmd hermes plugins list
    check_expect 'lapis-lazuli enabled'
    check_manual 'In a session, run /lps-ux'
    : ;;
  esac
}

# Antigravity CLI
h_antigravity() {
  case $1 in
  name) LL_H='Antigravity CLI' ;;
  detect)
    LL_WHY=
    if has_cmd agy; then LL_WHY="${LL_WHY:+$LL_WHY, }command agy"; fi
    if has_dir "$HOME"/.gemini/antigravity-cli; then LL_WHY="${LL_WHY:+$LL_WHY, }folder ~/.gemini/antigravity-cli"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='command agy or folder ~/.gemini/antigravity-cli' LL_ANCHOR='#antigravity-cli' ;;
  install)
    begin 'Antigravity CLI' agy
    for LL_plugin in $LL_PLUGINS; do
      if need_checkout; then
        step_run 0 'Antigravity installs only from a local folder, not from a repository' agy plugin install "$LL_checkout"/dist/antigravity/"$LL_plugin"
      fi
    done
    ;;
  update)
    begin 'Antigravity CLI' agy
    for LL_plugin in $LL_PLUGINS; do
      if need_checkout; then
        step_run 0 'installing a plugin again replaces its whole folder (agy 1.2.17, 2026-10-06: files the new version no longer has are gone)' agy plugin install "$LL_checkout"/dist/antigravity/"$LL_plugin"
      fi
    done
    ;;
  uninstall)
    begin 'Antigravity CLI' agy
    for LL_plugin in $LL_PLUGINS; do
      step_run 0 '' agy plugin uninstall "$LL_plugin"
    done
    ;;
  verify)
    check_cmd agy plugin list
    for LL_plugin in $LL_PLUGINS; do
      check_expect "$LL_plugin"' listed with its components'
    done
    check_manual 'In a new session, ask which skills are available, or run /lapis'
    : ;;
  esac
}

# Other Agent Skills harnesses
h_other() {
  case $1 in
  name) LL_H='Other Agent Skills harnesses' ;;
  detect)
    LL_WHY=
    LL_AGENTS_other=
    if has_dir "$HOME"/.cursor; then LL_AGENTS_other="${LL_AGENTS_other:+$LL_AGENTS_other }cursor"; LL_WHY="${LL_WHY:+$LL_WHY, }agent cursor"; fi
    if has_dir "$HOME"/.gemini; then LL_AGENTS_other="${LL_AGENTS_other:+$LL_AGENTS_other }gemini-cli"; LL_WHY="${LL_WHY:+$LL_WHY, }agent gemini-cli"; fi
    if has_dir "$HOME"/.copilot; then LL_AGENTS_other="${LL_AGENTS_other:+$LL_AGENTS_other }github-copilot"; LL_WHY="${LL_WHY:+$LL_WHY, }agent github-copilot"; fi
    if has_dir "$HOME"/.config/opencode; then LL_AGENTS_other="${LL_AGENTS_other:+$LL_AGENTS_other }opencode"; LL_WHY="${LL_WHY:+$LL_WHY, }agent opencode"; fi
    if has_dir "$HOME"/.codeium/windsurf; then LL_AGENTS_other="${LL_AGENTS_other:+$LL_AGENTS_other }windsurf"; LL_WHY="${LL_WHY:+$LL_WHY, }agent windsurf"; fi
    if has_dir "$HOME"/.kiro; then LL_AGENTS_other="${LL_AGENTS_other:+$LL_AGENTS_other }kiro-cli"; LL_WHY="${LL_WHY:+$LL_WHY, }agent kiro-cli"; fi
    [ -n "$LL_WHY" ] ;;
  lookfor) LL_LOOK='folder ~/.cursor or folder ~/.gemini or folder ~/.copilot or folder ~/.config/opencode or folder ~/.codeium/windsurf or folder ~/.kiro' LL_ANCHOR='#other-agent-skills-harnesses' ;;
  install)
    begin 'Other Agent Skills harnesses' npx
    note_whole
    for LL_agent in $LL_AGENTS_other; do
      step_run 0 'the subpath keeps the search inside dist/skills, so plugin copies are never picked up' npx -y skills add https://github.com/lapis-labs/lapis-lazuli/tree/release/dist/skills -g -y -a "$LL_agent"
    done
    step_manual 'Add dist/AGENTS.snippet.md to the agent'\''s instructions file for the session summary and MCP setup'
    snippet dist/AGENTS.snippet.md
    ;;
  update)
    begin 'Other Agent Skills harnesses' npx
    note_whole
    step_run 0 '' npx -y skills update -g -y
    snippet dist/AGENTS.snippet.md
    ;;
  uninstall)
    begin 'Other Agent Skills harnesses' npx
    for LL_agent in $LL_AGENTS_other; do
      for LL_skill in $LL_SKILLS; do
        step_run 0 '' npx -y skills remove "$LL_skill" -g -a "$LL_agent" -y
      done
    done
    ;;
  verify)
    for LL_agent in $LL_AGENTS_other; do
      check_cmd npx -y skills list -g -a "$LL_agent"
      check_expect 'every skill of the selected plugins is listed'
    done
    : ;;
  esac
}

harness() {
  case $1 in
  claude-code) h_claude_code "$2" ;;
  codex) h_codex "$2" ;;
  oh-my-pi) h_oh_my_pi "$2" ;;
  pi) h_pi "$2" ;;
  hermes) h_hermes "$2" ;;
  antigravity) h_antigravity "$2" ;;
  other) h_other "$2" ;;
  esac
}

add_want() {
  case $1 in
    --harness)
      in_list "$2" "$LL_ALL_HARNESSES" || usage_error "unknown harness '$2' (known: $LL_ALL_HARNESSES)"
      in_list "$2" "$LL_WANT_H" || LL_WANT_H="${LL_WANT_H:+$LL_WANT_H }$2"
      ;;
    --plugin)
      in_list "$2" "$LL_ALL_PLUGINS" || usage_error "unknown plugin '$2' (known: $LL_ALL_PLUGINS)"
      in_list "$2" "$LL_WANT_P" || LL_WANT_P="${LL_WANT_P:+$LL_WANT_P }$2"
      ;;
  esac
}

set_mode() {
  if [ "$LL_MODE" != install ] && [ "$LL_MODE" != "$1" ]; then
    usage_error "--update and --uninstall cannot be combined"
  fi
  LL_MODE=$1
}

parse_args() {
  while [ $# -gt 0 ]; do
    case $1 in
      --dry-run) LL_DRY=1 ;;
      --yes | -y) LL_YES=1 ;;
      --update) set_mode update ;;
      --uninstall) set_mode uninstall ;;
      --harness | --plugin)
        [ $# -ge 2 ] || usage_error "$1 needs a value"
        add_want "$1" "$2"
        shift
        ;;
      --harness=*) add_want --harness "${1#*=}" ;;
      --plugin=*) add_want --plugin "${1#*=}" ;;
      --help | -h)
        usage
        exit 0
        ;;
      *) usage_error "unknown option: $1" ;;
    esac
    shift
  done
}

main() {
  trap cleanup EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM HUP
  parse_args "$@"
  if [ -z "${HOME:-}" ]; then
    err "install.sh: HOME is not set"
    exit 1
  fi
  LL_os=$(uname -s 2>/dev/null) || LL_os=unknown
  case $LL_os in
    Darwin) LL_os=macOS ;;
    Linux) ;;
    *)
      err "install.sh: this script is for macOS and Linux (found $LL_os); on Windows use install.ps1: $LL_DOCS"
      exit 1
      ;;
  esac
  for LL_p in $LL_ALL_PLUGINS; do
    if [ -z "$LL_WANT_P" ] || in_list "$LL_p" "$LL_WANT_P"; then
      LL_PLUGINS="${LL_PLUGINS:+$LL_PLUGINS }$LL_p"
      LL_SKILLS="${LL_SKILLS:+$LL_SKILLS }$(skills_of "$LL_p")"
    fi
  done
  if [ "$LL_DRY" = 1 ]; then LL_how="$LL_MODE, dry run: nothing is changed"; else LL_how=$LL_MODE; fi
  say "LapisLazuli installer $LL_VERSION ($LL_how)"
  say "  system: $LL_os"
  if [ "$(id -u 2>/dev/null)" = 0 ]; then
    say "  warning: running as root, so harness settings go to $HOME; run it as yourself instead"
  fi
  say "  source: https://github.com/$LL_REPO at $LL_REF"
  say "  plugins: $LL_PLUGINS"
  LL_found=
  for LL_h in $LL_ALL_HARNESSES; do
    harness "$LL_h" name
    if harness "$LL_h" detect; then
      LL_found="${LL_found:+$LL_found }$LL_h"
      if skips_experimental "$LL_h"; then
        say "  found: $LL_H ($LL_WHY); experimental, so not installed unless named: --harness $LL_h"
      else
        say "  found: $LL_H ($LL_WHY)"
      fi
    fi
  done
  if [ -n "$LL_WANT_H" ]; then
    LL_absent=0
    for LL_h in $LL_ALL_HARNESSES; do
      in_list "$LL_h" "$LL_WANT_H" || continue
      if in_list "$LL_h" "$LL_found"; then
        LL_TARGETS="${LL_TARGETS:+$LL_TARGETS }$LL_h"
        continue
      fi
      harness "$LL_h" name
      harness "$LL_h" lookfor
      err "install.sh: $LL_H is not installed here: found no $LL_LOOK."
      err "  Install $LL_H first, or leave out --harness $LL_h. Guide: $LL_DOCS$LL_ANCHOR"
      LL_absent=1
    done
    [ "$LL_absent" = 0 ] || exit 1
  else
    for LL_h in $LL_found; do
      skips_experimental "$LL_h" || LL_TARGETS="${LL_TARGETS:+$LL_TARGETS }$LL_h"
    done
  fi
  if [ -z "$LL_TARGETS" ]; then
    if [ -n "$LL_found" ]; then
      say "  no harness to install: the ones found are experimental; see $LL_DOCS#identify-your-harness"
    else
      say "  no supported harness found; see $LL_DOCS#identify-your-harness"
    fi
  fi

  if [ "$LL_MODE" != uninstall ]; then
    LL_TOOL=$(cli_tool install) || LL_TOOL=
    if [ -z "$LL_TOOL" ] && [ "$LL_DRY" = 0 ]; then
      err "install.sh: the CLI needs $LL_CLI_NEEDS on PATH; install one and run this again. Guide: $LL_DOCS#cli-and-optional-components"
      exit 1
    fi
    begin "$LL_CLI_NAME"
    if [ -n "$LL_TOOL" ]; then
      say "  with: $LL_TOOL"
      cli_steps install "$LL_TOOL"
    else
      failed "CLI: no $LL_CLI_NEEDS on PATH"
    fi
  fi

  for LL_h in $LL_TARGETS; do
    harness "$LL_h" "$LL_MODE"
  done

  if [ "$LL_MODE" = uninstall ]; then
    begin "$LL_CLI_NAME"
    if [ -n "$LL_WANT_H" ] || ! all_plugins; then
      say "  kept: the CLI goes only with every plugin from every harness"
    elif LL_TOOL=$(cli_tool uninstall); then
      cli_steps uninstall "$LL_TOOL"
    else
      say "  no $LL_CLI_NEEDS on PATH; remove the CLI with the tool that installed it"
    fi
  else
    begin "Check the CLI"
    cli_verify
    for LL_h in $LL_TARGETS; do
      harness "$LL_h" name
      harness "$LL_h" verify
    done
  fi

  print_block "== Checks to run" "$LL_CHECKS" "  "
  print_block "== To do by hand" "$LL_TODO" "  "
  [ "$LL_MODE" = uninstall ] || show_snippets
  print_block "== Notes" "$LL_NOTES" "  "
  say ""
  say "== Summary"
  if [ "$LL_DRY" = 1 ]; then
    say "  dry run: nothing was changed"
  elif [ -n "$LL_CHANGES" ]; then
    say "  changed:"
    printf '%s' "$LL_CHANGES" | while IFS= read -r LL_l; do say "    $LL_l"; done
  else
    say "  nothing was changed"
  fi
  if [ -n "$LL_FAILED" ]; then
    say "  failed:"
    printf '%s' "$LL_FAILED" | while IFS= read -r LL_l; do say "    $LL_l"; done
    exit 1
  fi
  exit 0
}

main "$@"
