# LapisLazuli installer for Windows (Windows PowerShell 5.1 or later, or PowerShell 7).
# Generated by tools/build/installers.py from install/harnesses.yaml; do not edit.
# Every harness command is an argv list from that file, run as separate arguments; nothing goes
# through Invoke-Expression.
Set-StrictMode -Version 2.0

$script:Version = '0.1.0'
$script:Repo = 'lapis-labs/lapis-lazuli'
$script:Ref = 'release'
$script:Raw = 'https://raw.githubusercontent.com/lapis-labs/lapis-lazuli/release'
$script:Docs = 'https://github.com/lapis-labs/lapis-lazuli/blob/release/INSTALLATION.md'
$script:AllPlugins = @('lapis', 'ultramarine', 'lazuli')
$script:AllHarnesses = @('claude-code', 'codex', 'oh-my-pi', 'pi', 'hermes', 'other')
$script:Experimental = @('pi', 'hermes')
$script:CliName = 'CLI (lapis-design, lazuli)'
$script:CliNeeds = 'uv or pipx'
$script:SkillsOf = @{
  'lapis' = @('lapis', 'lps-ux', 'lps-copy', 'lps-system')
  'ultramarine' = @('ultramarine', 'ulm-maintain', 'ulm-release')
  'lazuli' = @('lazuli', 'lzl-fonts', 'lzl-color', 'lzl-research')
}
$script:Usage = @'
Usage: install.ps1 [options]

Installs the LapisLazuli CLI (lapis-design, lazuli) with uv or pipx and adds the plugins to every
harness it finds. Guide: https://github.com/lapis-labs/lapis-lazuli/blob/release/INSTALLATION.md

Options:
  --dry-run        print every command it would run; change nothing
  --harness ID     only this harness (repeatable): claude-code, codex, oh-my-pi, pi, hermes, other
                   experimental, so installed only when named here: pi, hermes
  --plugin NAME    only this plugin (repeatable; default: all): lapis, ultramarine, lazuli
  --update         run the update steps and reinstall the CLI from release
  --uninstall      run the removal steps; a catalog goes only with every plugin, and
                   the CLI only with every plugin from every harness
  --yes, -y        answer yes to every question
  --help, -h       show this help
'@
$script:Mode = 'install'
$script:Dry = $false
$script:Yes = $false
$script:WantH = @()
$script:WantP = @()
$script:Plugins = @()
$script:Skills = @()
$script:Agents = @{ 'other' = @() }
$script:H = ''
$script:Manual = $false
$script:Sha = ''
$script:ShaState = ''
$script:Tool = ''
$script:Why = @()
$script:Look = ''
$script:Anchor = ''
$script:Todo = New-Object 'System.Collections.Generic.List[string]'
$script:Checks = New-Object 'System.Collections.Generic.List[string]'
$script:Notes = New-Object 'System.Collections.Generic.List[string]'
$script:Changes = New-Object 'System.Collections.Generic.List[string]'
$script:Failed = New-Object 'System.Collections.Generic.List[string]'
$script:Snippets = New-Object 'System.Collections.Generic.List[string]'

function Say([string]$Text) { Write-Host $Text }
function Err([string]$Text) { [Console]::Error.WriteLine($Text) }

function Show-UsageError([string]$Text) {
  Err ('install.ps1: ' + $Text)
  Err $script:Usage
  return 2
}

function Test-Cmd([string]$Name) {
  return [bool](Get-Command -Name $Name -CommandType Application, ExternalScript -ErrorAction SilentlyContinue)
}
function Test-Dir([string]$Path) { return (Test-Path -LiteralPath $Path -PathType Container) }
function Get-HomePath([string]$Rel) {
  $sep = [string][IO.Path]::DirectorySeparatorChar
  return ($HOME.TrimEnd('/', '\') + $sep + $Rel.Replace('/', $sep))
}
function Test-Slug([string]$Word) { return ($Word -cmatch '^[a-z0-9-]+$') }
function Test-SkipExperimental([string]$Id) {
  return ($script:Mode -ceq 'install' -and $script:WantH.Count -eq 0 -and ($script:Experimental -ccontains $Id))
}
function Select-Among([string[]]$Names) { return @(@($script:Plugins) | Where-Object { $Names -ccontains $_ }) }
function Test-Selected([string]$Name) { return (@($script:Plugins) -ccontains $Name) }
function Test-AllPlugins { return ((@($script:Plugins) -join ' ') -ceq (@($script:AllPlugins) -join ' ')) }

# Format-Arg: one argument, quoted for PowerShell when it needs quotes.
function Format-Arg([string]$Arg) {
  if ($Arg -cmatch '^[A-Za-z0-9_./:+-][A-Za-z0-9_./:@+-]*$') { return $Arg }
  return ("'" + $Arg.Replace("'", "''") + "'")
}
function Format-Argv([string[]]$Argv) { return ((@($Argv) | ForEach-Object { Format-Arg $_ }) -join ' ') }

function Add-Todo([string]$Text) { $script:Todo.Add('- ' + $Text) }
function Add-Change([string]$Text) { $script:Changes.Add('- ' + $Text) }
function Add-Failure([string]$Text) {
  $script:Failed.Add('- ' + $Text)
  Say ('  failed: ' + $Text)
}
function Add-Note([string]$Text) {
  if (-not $Text) { return }
  $line = '- ' + $script:H + ': ' + $Text
  if (-not $script:Notes.Contains($line)) { $script:Notes.Add($line) }
}
function Write-WholeNote {
  if (-not (Test-AllPlugins)) { Say ('  note: ' + $script:H + ' takes every plugin at once; --plugin does not narrow it') }
}
function Add-CheckCmd([string[]]$Argv) { $script:Checks.Add('- ' + $script:H + ': ' + (Format-Argv $Argv)) }
function Add-CheckExpect([string]$Text) { $script:Checks.Add('    expect: ' + $Text) }
function Add-CheckManual([string]$Text) { $script:Checks.Add('- ' + $script:H + ': ' + $Text) }
function Add-Snippet([string]$Path) { if (-not $script:Snippets.Contains($Path)) { $script:Snippets.Add($Path) } }

function Write-Block([string]$Title, $Lines, [string]$Indent) {
  if ($Lines.Count -eq 0) { return }
  Say ''
  Say $Title
  foreach ($line in $Lines) { Say ($Indent + $line) }
}

# Ask: yes only for y or yes (--yes answers for the user).
function Ask([string]$Question) {
  if ($script:Yes) {
    Say ('  ' + $Question + ' [y/N] y (--yes)')
    return $true
  }
  $answer = Read-Host ('  ' + $Question + ' [y/N]')
  return ([string]$answer -match '^\s*(y|yes)\s*$')
}

function Get-Url([string]$Url, [string]$Dest) {
  $ProgressPreference = 'SilentlyContinue'
  try {
    Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $Dest -ErrorAction Stop
    return $true
  } catch {
    Say ('  ' + $_.Exception.Message)
    return $false
  }
}

function Invoke-Argv([string[]]$Argv) {
  $rest = @()
  if ($Argv.Count -gt 1) { $rest = $Argv[1..($Argv.Count - 1)] }
  try {
    $cmd = Get-Command -Name $Argv[0] -CommandType Application, ExternalScript -ErrorAction Stop | Select-Object -First 1
    $global:LASTEXITCODE = 0
    & $cmd @rest | Out-Host
  } catch {
    Say ('  ' + $_.Exception.Message)
    return 127
  }
  return [int]$global:LASTEXITCODE
}

# Start-Phase: start a section; when a command is missing, its steps become a to-do list.
function Start-Phase([string]$Name, [string[]]$Commands) {
  $script:H = $Name
  $script:Manual = $false
  $missing = @(@($Commands) | Where-Object { -not (Test-Cmd $_) })
  Say ''
  Say ('== ' + $Name)
  if ($missing.Count -gt 0) {
    $script:Manual = $true
    Say ('  not on PATH: ' + ($missing -join ', ') + "; the steps are listed under 'To do by hand'")
  }
}

function Skip-All([string]$Text) { Say ('  not now (only when every plugin is removed): ' + $Text) }

function Invoke-Run([bool]$AskFirst, [string]$Note, [string[]]$Argv) {
  $line = Format-Argv $Argv
  Add-Note $Note
  if ($script:Manual) {
    Add-Todo ($script:H + ': ' + $line)
    return
  }
  if ($script:Dry) {
    if ($AskFirst -and -not $script:Yes) { Say ('  would ask, then run: ' + $line) } else { Say ('  would run: ' + $line) }
    return
  }
  if ($AskFirst) {
    if ($Note) { Say ('  note: ' + $Note) }
    if (-not (Ask ('Run ' + $line + ' ?'))) {
      Say ('  skipped: ' + $line)
      Add-Todo ($script:H + ' (you declined): ' + $line)
      return
    }
  }
  Say ('  run: ' + $line)
  $code = Invoke-Argv $Argv
  if ($code -eq 0) { Add-Change ($script:H + ': ran ' + $line) } else { Add-Failure ($script:H + ': ' + $line + ' (exit ' + $code + ')') }
}

function Invoke-Copy([bool]$AskFirst, [string]$Note, [string]$Source, [string]$Dest) {
  $url = $script:Raw + '/' + $Source
  Add-Note $Note
  if ($script:Manual) {
    Add-Todo ($script:H + ': copy ' + $url + ' to ' + $Dest)
    return
  }
  if ($script:Dry) {
    if ($AskFirst -and -not $script:Yes) { Say ('  would ask, then copy: ' + $url + ' -> ' + $Dest) } else { Say ('  would copy: ' + $url + ' -> ' + $Dest) }
    return
  }
  $tmp = [IO.Path]::GetTempFileName()
  try {
    Say ('  download: ' + $url)
    if (-not (Get-Url $url $tmp)) {
      Add-Failure ($script:H + ': could not download ' + $url)
      return
    }
    if ((Test-Path -LiteralPath $Dest -PathType Leaf) -and ((Get-FileHash -LiteralPath $tmp).Hash -eq (Get-FileHash -LiteralPath $Dest).Hash)) {
      Say ('  unchanged: ' + $Dest)
      return
    }
    $name = $Source.Substring($Source.LastIndexOf('/') + 1)
    if ($AskFirst -and -not (Ask ('Copy ' + $name + ' to ' + $Dest + ' ?'))) {
      Say ('  skipped: copy to ' + $Dest)
      Add-Todo ($script:H + ' (you declined): copy ' + $url + ' to ' + $Dest)
      return
    }
    try {
      New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Dest) -ErrorAction Stop | Out-Null
      Copy-Item -LiteralPath $tmp -Destination $Dest -Force -ErrorAction Stop
      Say ('  copied: ' + $Dest)
      Add-Change ($script:H + ': copied ' + $url + ' to ' + $Dest)
    } catch {
      Add-Failure ($script:H + ': could not write ' + $Dest + ': ' + $_.Exception.Message)
    }
  } finally {
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
  }
}

function Invoke-Remove([bool]$AskFirst, [string]$Note, [string]$Path) {
  $directory = $Path.EndsWith([string][IO.Path]::DirectorySeparatorChar)
  $action = if ($directory) { 'remove folder if empty: ' } else { 'remove ' }
  Add-Note $Note
  if ($script:Manual) {
    Add-Todo ($script:H + ': ' + $action + $Path)
    return
  }
  if ($directory) {
    $folder = $Path.Substring(0, $Path.Length - 1)
    $item = Get-Item -LiteralPath $folder -Force -ErrorAction SilentlyContinue
    if ($null -eq $item) {
      if (Test-Path -LiteralPath $folder) {
        Say ('  kept (unreadable): ' + $Path)
        Add-Todo ($script:H + ': ' + $action + $Path)
      } else {
        Say ('  already absent: ' + $Path)
      }
      return
    }
    $reason = if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) { 'symbolic link' }
              elseif (-not $item.PSIsContainer) { 'not a folder' }
              else { '' }
    if ($reason) {
      Say ('  kept (' + $reason + '): ' + $Path)
      Add-Todo ($script:H + ': ' + $action + $Path)
      return
    }
  } elseif (-not (Test-Path -LiteralPath $Path)) {
    Say ('  already absent: ' + $Path)
    return
  }
  if ($script:Dry) {
    if ($AskFirst -and -not $script:Yes) { Say ('  would ask, then ' + $action + $Path) } else { Say ('  would ' + $action + $Path) }
    return
  }
  if ($AskFirst -and -not (Ask ('Remove ' + $Path + ' ?'))) {
    Say ('  skipped: ' + $action + $Path)
    Add-Todo ($script:H + ' (you declined): ' + $action + $Path)
    return
  }
  if ($directory) {
    try {
      if (@(Get-ChildItem -LiteralPath $folder -Force -ErrorAction Stop | Select-Object -First 1).Count -gt 0) {
        Say ('  kept (not empty): ' + $Path)
        Add-Todo ($script:H + ': ' + $action + $Path)
        return
      }
    } catch {
      Say ('  kept (unreadable): ' + $Path)
      Add-Todo ($script:H + ': ' + $action + $Path)
      return
    }
    try {
      [System.IO.Directory]::Delete($folder, $false)
      Say ('  removed empty folder: ' + $Path)
      Add-Change ($script:H + ': removed empty folder ' + $Path)
    } catch {
      Say ('  kept (could not remove empty folder): ' + $Path)
      Add-Todo ($script:H + ': ' + $action + $Path)
    }
    return
  }
  try {
    Remove-Item -LiteralPath $Path -Force -ErrorAction Stop
    Say ('  removed: ' + $Path)
    Add-Change ($script:H + ': removed ' + $Path)
  } catch {
    Add-Failure ($script:H + ': could not remove ' + $Path + ': ' + $_.Exception.Message)
  }
}

function Invoke-Manual([string]$Text) { Add-Todo ($script:H + ': ' + $Text) }

# Get-Sha: set $script:Sha to the full commit the release ref points to.
function Get-Sha {
  $url = 'https://github.com/' + $script:Repo
  $refName = 'refs/heads/' + $script:Ref
  if ($script:Dry) {
    if (-not $script:Sha) { Say ('  would run: git ls-remote ' + $url + ' ' + $refName) }
    $script:Sha = '<commit>'
    return $true
  }
  if ($script:ShaState -eq 'ok') { return $true }
  if (-not $script:ShaState) {
    $script:ShaState = 'failed'
    if (Test-Cmd 'git') {
      Say ('  run: git ls-remote ' + $url + ' ' + $refName)
      $saved = $env:GIT_TERMINAL_PROMPT
      $env:GIT_TERMINAL_PROMPT = '0'
      try { $out = @(& git ls-remote $url $refName) } catch { $out = @() }
      $env:GIT_TERMINAL_PROMPT = $saved
      $first = ''
      if ($out.Count -gt 0) { $first = ([string]$out[0] -split '\s+')[0] }
      if ($first -cmatch '^[0-9a-f]{40}$') {
        $script:Sha = $first
        $script:ShaState = 'ok'
        Say ('  commit: ' + $first)
        return $true
      }
    }
    Say ('  could not read the commit ' + $script:Ref + ' points to (git ls-remote ' + $url + ' ' + $refName + ')')
  }
  if ($script:Manual) {
    $script:Sha = '<commit>'
    return $true
  }
  Add-Failure ($script:H + ': skipped a step that needs the commit of ' + $script:Ref)
  return $false
}

function Invoke-Verify([string]$Expect, [string[]]$Argv) {
  $line = Format-Argv $Argv
  if ($script:Dry) {
    Say ('  would check: ' + $line)
    Say ('    expect: ' + $Expect)
    return
  }
  if (-not (Test-Cmd $Argv[0])) {
    Add-Failure ('CLI: ' + $Argv[0] + ' is not on PATH; open a new terminal' + (Get-PathHint))
    return
  }
  Say ('  check: ' + $line)
  Say ('    expect: ' + $Expect)
  $code = Invoke-Argv $Argv
  if ($code -ne 0) { Add-Failure ('CLI: ' + $line + ' (exit ' + $code + ')') }
}

function Show-Snippets {
  foreach ($path in $script:Snippets) {
    $url = $script:Raw + '/' + $path
    Say ''
    Say ('== Instructions snippet: ' + $path)
    Say "  Add it to your agent's instructions file yourself; this script never edits one."
    if ($script:Dry) {
      Say ('  would show: ' + $url)
      continue
    }
    $tmp = [IO.Path]::GetTempFileName()
    if (Get-Url $url $tmp) {
      Say ('----- ' + $path + ' -----')
      foreach ($line in (Get-Content -LiteralPath $tmp)) { Say $line }
      Say ('----- end of ' + $path + ' -----')
    } else {
      Say ('  could not download it; open ' + $url)
    }
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
  }
}

# The CLI: the first tool on PATH wins.
function Get-CliTool([string]$Phase) {
  if ($Phase -eq 'install') {
    if (Test-Cmd 'uv') { return 'uv' }
    if (Test-Cmd 'pipx') { return 'pipx' }
  }
  if ($Phase -eq 'uninstall') {
    if (Test-Cmd 'uv') { return 'uv' }
    if (Test-Cmd 'pipx') { return 'pipx' }
  }
  return ''
}

function Invoke-CliSteps([string]$Phase, [string]$Tool) {
  if ($Phase -eq 'install' -and $Tool -eq 'uv') {
    Invoke-Run $false '' @('uv', 'tool', 'install', '--force', 'git+https://github.com/lapis-labs/lapis-lazuli@release')
  }
  if ($Phase -eq 'install' -and $Tool -eq 'pipx') {
    Invoke-Run $false '' @('pipx', 'install', '--force', 'git+https://github.com/lapis-labs/lapis-lazuli@release')
  }
  if ($Phase -eq 'uninstall' -and $Tool -eq 'uv') {
    Invoke-Run $false '' @('uv', 'tool', 'uninstall', 'lapis-design')
  }
  if ($Phase -eq 'uninstall' -and $Tool -eq 'pipx') {
    Invoke-Run $false '' @('pipx', 'uninstall', 'lapis-design')
  }
}

function Invoke-CliVerify {
  Invoke-Verify 'prints the version of release' @('lapis-design', '--version')
  Invoke-Verify 'exit code 0' @('lazuli', 'doctor')
}

function Get-PathHint {
  if ($script:Tool -eq 'uv') { return '; or run: uv tool update-shell' }
  if ($script:Tool -eq 'pipx') { return '; or run: pipx ensurepath' }
  return ''
}

# Claude Code
function h_claude_code([string]$Phase) {
  switch ($Phase) {
    'name' { $script:H = 'Claude Code' }
    'detect' {
      $script:Why = @()
      if (Test-Cmd 'claude') { $script:Why += 'command claude' }
      if (Test-Dir (Get-HomePath '.claude')) { $script:Why += 'folder ~/.claude' }
    }
    'lookfor' { $script:Look = 'command claude or folder ~/.claude'; $script:Anchor = '#claude-code' }
    'install' {
      Start-Phase 'Claude Code' @('claude')
      Invoke-Run $false '' @('claude', 'plugin', 'marketplace', 'add', 'lapis-labs/lapis-lazuli@release')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('claude', 'plugin', 'install', ('' + $Plugin + '@lapis-lazuli'), '-s', 'user')
      }
    }
    'update' {
      Start-Phase 'Claude Code' @('claude')
      Invoke-Run $false '' @('claude', 'plugin', 'marketplace', 'update', 'lapis-lazuli')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false 'the new version loads in the next session or after /reload-plugins' @('claude', 'plugin', 'update', ('' + $Plugin + '@lapis-lazuli'))
      }
    }
    'uninstall' {
      Start-Phase 'Claude Code' @('claude')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('claude', 'plugin', 'uninstall', ('' + $Plugin + '@lapis-lazuli'), '-s', 'user')
      }
      if (Test-AllPlugins) {
        Invoke-Run $false 'removing the catalog uninstalls every plugin installed from it' @('claude', 'plugin', 'marketplace', 'remove', 'lapis-lazuli')
      } else {
        Skip-All 'claude plugin marketplace remove lapis-lazuli'
      }
    }
    'verify' {
      Add-CheckCmd @('claude', 'plugin', 'list', '--json')
      foreach ($Plugin in @($script:Plugins)) {
        Add-CheckExpect ('an enabled entry ' + $Plugin + '@lapis-lazuli with no errors')
      }
      Add-CheckManual 'In a session, run /lapis:lapis and check that the skill loads'
    }
  }
}

# OpenAI Codex CLI
function h_codex([string]$Phase) {
  switch ($Phase) {
    'name' { $script:H = 'OpenAI Codex CLI' }
    'detect' {
      $script:Why = @()
      if (Test-Cmd 'codex') { $script:Why += 'command codex' }
      if (Test-Dir (Get-HomePath '.codex')) { $script:Why += 'folder ~/.codex' }
    }
    'lookfor' { $script:Look = 'command codex or folder ~/.codex'; $script:Anchor = '#openai-codex-cli' }
    'install' {
      Start-Phase 'OpenAI Codex CLI' @('codex')
      Add-Note 'needs version 0.153.0 or later'
      Invoke-Run $false '' @('codex', 'plugin', 'marketplace', 'add', 'lapis-labs/lapis-lazuli', '--ref', 'release')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('codex', 'plugin', 'add', ('' + $Plugin + '@lapis-lazuli'))
      }
      if (Test-Selected 'ultramarine') {
        Invoke-Copy $true '' 'dist/codex/agents/ulm-critic.toml' (Get-HomePath '.codex/agents/ulm-critic.toml')
      }
      Invoke-Manual 'Open /hooks in Codex and trust the lazuli session-start hook; it does not run until trusted'
    }
    'update' {
      Start-Phase 'OpenAI Codex CLI' @('codex')
      Add-Note 'needs version 0.153.0 or later'
      Invoke-Run $false 'there is no per-plugin update; new skills appear in the next session' @('codex', 'plugin', 'marketplace', 'upgrade', 'lapis-lazuli')
      if (Test-Selected 'ultramarine') {
        Invoke-Copy $true '' 'dist/codex/agents/ulm-critic.toml' (Get-HomePath '.codex/agents/ulm-critic.toml')
      }
    }
    'uninstall' {
      Start-Phase 'OpenAI Codex CLI' @('codex')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('codex', 'plugin', 'remove', ('' + $Plugin + '@lapis-lazuli'))
      }
      if (Test-AllPlugins) {
        Invoke-Run $false '' @('codex', 'plugin', 'marketplace', 'remove', 'lapis-lazuli')
      } else {
        Skip-All 'codex plugin marketplace remove lapis-lazuli'
      }
      if (Test-AllPlugins) {
        Invoke-Remove $false '' (Get-HomePath '.codex/plugins/cache/lapis-lazuli/')
      } else {
        Skip-All 'remove folder if empty: ~/.codex/plugins/cache/lapis-lazuli/'
      }
      if (Test-Selected 'ultramarine') {
        Invoke-Remove $true '' (Get-HomePath '.codex/agents/ulm-critic.toml')
      }
    }
    'verify' {
      Add-CheckCmd @('codex', 'plugin', 'list', '--json')
      foreach ($Plugin in @($script:Plugins)) {
        Add-CheckExpect ('' + $Plugin + '@lapis-lazuli installed and enabled')
      }
      Add-CheckManual 'In a new session, type $lapis:lps-ux and check that the skill is offered'
    }
  }
}

# Oh-My-Pi
function h_oh_my_pi([string]$Phase) {
  switch ($Phase) {
    'name' { $script:H = 'Oh-My-Pi' }
    'detect' {
      $script:Why = @()
      if (Test-Cmd 'omp') { $script:Why += 'command omp' }
      if (Test-Dir (Get-HomePath '.omp')) { $script:Why += 'folder ~/.omp' }
    }
    'lookfor' { $script:Look = 'command omp or folder ~/.omp'; $script:Anchor = '#oh-my-pi' }
    'install' {
      Start-Phase 'Oh-My-Pi' @('omp')
      Invoke-Run $false '' @('omp', 'plugin', 'marketplace', 'add', 'lapis-labs/lapis-lazuli')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('omp', 'plugin', 'install', '--scope', 'user', ('' + $Plugin + '@lapis-lazuli'))
      }
      Invoke-Manual 'Restart omp so the session-start extension loads; /reload-plugins refreshes skills and MCP only'
    }
    'update' {
      Start-Phase 'Oh-My-Pi' @('omp')
      Invoke-Run $false '' @('omp', 'plugin', 'marketplace', 'update', 'lapis-lazuli')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('omp', 'plugin', 'upgrade', '--scope', 'user', ('' + $Plugin + '@lapis-lazuli'))
      }
    }
    'uninstall' {
      Start-Phase 'Oh-My-Pi' @('omp')
      foreach ($Plugin in @($script:Plugins)) {
        Invoke-Run $false '' @('omp', 'plugin', 'uninstall', '--scope', 'user', ('' + $Plugin + '@lapis-lazuli'))
      }
      if (Test-AllPlugins) {
        Invoke-Run $false '' @('omp', 'plugin', 'marketplace', 'remove', 'lapis-lazuli')
      } else {
        Skip-All 'omp plugin marketplace remove lapis-lazuli'
      }
    }
    'verify' {
      Add-CheckCmd @('omp', 'plugin', 'list')
      foreach ($Plugin in @($script:Plugins)) {
        Add-CheckExpect ('' + $Plugin + '@lapis-lazuli listed and enabled')
      }
      Add-CheckManual 'In a session, run /skill:lps-ux'
    }
  }
}

# pi
function h_pi([string]$Phase) {
  switch ($Phase) {
    'name' { $script:H = 'pi' }
    'detect' {
      $script:Why = @()
      if (Test-Cmd 'pi') { $script:Why += 'command pi' }
      if (Test-Dir (Get-HomePath '.pi/agent')) { $script:Why += 'folder ~/.pi/agent' }
    }
    'lookfor' { $script:Look = 'command pi or folder ~/.pi/agent'; $script:Anchor = '#pi' }
    'install' {
      Start-Phase 'pi' @('pi')
      Write-WholeNote
      Invoke-Run $false '' @('pi', 'install', 'git:github.com/lapis-labs/lapis-lazuli@release')
    }
    'update' {
      Start-Phase 'pi' @('pi')
      Write-WholeNote
      Invoke-Run $false 'pi keys git packages by repository without the ref, so installing again replaces the older install' @('pi', 'install', 'git:github.com/lapis-labs/lapis-lazuli@release')
    }
    'uninstall' {
      Start-Phase 'pi' @('pi')
      if (Test-AllPlugins) {
        Invoke-Run $false 'one package carries every plugin''s skills, so it goes only when every plugin is removed' @('pi', 'remove', 'git:github.com/lapis-labs/lapis-lazuli')
      } else {
        Skip-All 'pi remove git:github.com/lapis-labs/lapis-lazuli'
      }
    }
    'verify' {
      Add-CheckCmd @('pi', 'list')
      Add-CheckExpect 'the lapis-labs/lapis-lazuli package is listed'
      Add-CheckManual 'In a session, run /skill:lps-ux'
    }
  }
}

# Hermes Agent
function h_hermes([string]$Phase) {
  switch ($Phase) {
    'name' { $script:H = 'Hermes Agent' }
    'detect' {
      $script:Why = @()
      if (Test-Cmd 'hermes') { $script:Why += 'command hermes' }
      if (Test-Dir (Get-HomePath '.hermes')) { $script:Why += 'folder ~/.hermes' }
    }
    'lookfor' { $script:Look = 'command hermes or folder ~/.hermes'; $script:Anchor = '#hermes-agent' }
    'install' {
      Start-Phase 'Hermes Agent' @('hermes')
      foreach ($Skill in @($script:Skills)) {
        Invoke-Run $false '' @('hermes', 'skills', 'install', ('lapis-labs/lapis-lazuli/dist/skills/' + $Skill), '--yes')
      }
      if (Get-Sha) {
        Invoke-Run $true 'plugins are disabled by default; --enable turns this one on. --ref takes only a full commit' @('hermes', 'plugins', 'install', 'lapis-labs/lapis-lazuli/plugins/hermes/lapis-lazuli', '--ref', ('' + $script:Sha), '--enable')
      }
      Invoke-Run $false '' @('hermes', 'mcp', 'add', 'lapis-lazuli', '--command', 'lapis-design', '--args', 'mcp')
    }
    'update' {
      Start-Phase 'Hermes Agent' @('hermes')
      Write-WholeNote
      Invoke-Run $false '' @('hermes', 'skills', 'update')
      if (Get-Sha) {
        Invoke-Run $true 'update refuses to move a pinned plugin; reinstall at the new commit' @('hermes', 'plugins', 'install', 'lapis-labs/lapis-lazuli/plugins/hermes/lapis-lazuli', '--ref', ('' + $script:Sha), '--enable', '--force')
      }
    }
    'uninstall' {
      Start-Phase 'Hermes Agent' @('hermes')
      foreach ($Skill in @($script:Skills)) {
        Invoke-Run $false '' @('hermes', 'skills', 'uninstall', ('' + $Skill))
      }
      if (Test-AllPlugins) {
        Invoke-Run $false 'the one Hermes plugin serves every skill''s session summary' @('hermes', 'plugins', 'remove', 'lapis-lazuli')
      } else {
        Skip-All 'hermes plugins remove lapis-lazuli'
      }
      if (Test-AllPlugins) {
        Invoke-Run $false '' @('hermes', 'mcp', 'remove', 'lapis-lazuli')
      } else {
        Skip-All 'hermes mcp remove lapis-lazuli'
      }
    }
    'verify' {
      Add-CheckCmd @('hermes', 'skills', 'list')
      Add-CheckExpect 'every skill of the selected plugins is listed'
      Add-CheckCmd @('hermes', 'plugins', 'list')
      Add-CheckExpect 'lapis-lazuli enabled'
      Add-CheckManual 'In a session, run /lps-ux'
    }
  }
}

# Other Agent Skills harnesses
function h_other([string]$Phase) {
  switch ($Phase) {
    'name' { $script:H = 'Other Agent Skills harnesses' }
    'detect' {
      $script:Why = @()
      $script:Agents['other'] = @()
      if ((Test-Dir (Get-HomePath '.cursor'))) { $script:Agents['other'] += 'cursor'; $script:Why += 'agent cursor' }
      if ((Test-Dir (Get-HomePath '.gemini'))) { $script:Agents['other'] += 'gemini-cli'; $script:Why += 'agent gemini-cli' }
      if ((Test-Dir (Get-HomePath '.copilot'))) { $script:Agents['other'] += 'github-copilot'; $script:Why += 'agent github-copilot' }
      if ((Test-Dir (Get-HomePath '.config/opencode'))) { $script:Agents['other'] += 'opencode'; $script:Why += 'agent opencode' }
      if ((Test-Dir (Get-HomePath '.codeium/windsurf'))) { $script:Agents['other'] += 'windsurf'; $script:Why += 'agent windsurf' }
      if ((Test-Dir (Get-HomePath '.kiro'))) { $script:Agents['other'] += 'kiro-cli'; $script:Why += 'agent kiro-cli' }
    }
    'lookfor' { $script:Look = 'folder ~/.cursor or folder ~/.gemini or folder ~/.copilot or folder ~/.config/opencode or folder ~/.codeium/windsurf or folder ~/.kiro'; $script:Anchor = '#other-agent-skills-harnesses' }
    'install' {
      Start-Phase 'Other Agent Skills harnesses' @('npx')
      Write-WholeNote
      foreach ($Agent in @($script:Agents['other'])) {
        Invoke-Run $false 'the subpath keeps the search inside dist/skills, so plugin copies are never picked up' @('npx', '-y', 'skills', 'add', 'https://github.com/lapis-labs/lapis-lazuli/tree/release/dist/skills', '-g', '-y', '-a', ('' + $Agent))
      }
      Invoke-Manual 'Add dist/AGENTS.snippet.md to the agent''s instructions file for the session summary and MCP setup'
      Add-Snippet 'dist/AGENTS.snippet.md'
    }
    'update' {
      Start-Phase 'Other Agent Skills harnesses' @('npx')
      Write-WholeNote
      Invoke-Run $false '' @('npx', '-y', 'skills', 'update', '-g', '-y')
      Add-Snippet 'dist/AGENTS.snippet.md'
    }
    'uninstall' {
      Start-Phase 'Other Agent Skills harnesses' @('npx')
      foreach ($Agent in @($script:Agents['other'])) {
        foreach ($Skill in @($script:Skills)) {
          Invoke-Run $false '' @('npx', '-y', 'skills', 'remove', ('' + $Skill), '-g', '-a', ('' + $Agent), '-y')
        }
      }
    }
    'verify' {
      foreach ($Agent in @($script:Agents['other'])) {
        Add-CheckCmd @('npx', '-y', 'skills', 'list', '-g', '-a', ('' + $Agent))
        Add-CheckExpect 'every skill of the selected plugins is listed'
      }
    }
  }
}

function Invoke-Harness([string]$Id, [string]$Phase) {
  switch -CaseSensitive ($Id) {
    'claude-code' { h_claude_code $Phase }
    'codex' { h_codex $Phase }
    'oh-my-pi' { h_oh_my_pi $Phase }
    'pi' { h_pi $Phase }
    'hermes' { h_hermes $Phase }
    'other' { h_other $Phase }
  }
}

function Invoke-Main([object[]]$Arguments) {
  $i = 0
  $n = @($Arguments).Count
  while ($i -lt $n) {
    $a = [string]$Arguments[$i]
    $value = $null
    if ($a -clike '--harness=*' -or $a -clike '--plugin=*') {
      $value = $a.Substring($a.IndexOf('=') + 1)
      $a = $a.Substring(0, $a.IndexOf('='))
    } elseif ($a -ceq '--harness' -or $a -ceq '--plugin') {
      if ($i + 1 -ge $n) { return (Show-UsageError ($a + ' needs a value')) }
      $i++
      $value = [string]$Arguments[$i]
    }
    if ($a -ceq '--dry-run') { $script:Dry = $true }
    elseif ($a -ceq '--yes' -or $a -ceq '-y') { $script:Yes = $true }
    elseif ($a -ceq '--update' -or $a -ceq '--uninstall') {
      $mode = $a.Substring(2)
      if ($script:Mode -ne 'install' -and $script:Mode -ne $mode) { return (Show-UsageError '--update and --uninstall cannot be combined') }
      $script:Mode = $mode
    }
    elseif ($a -ceq '--harness') {
      if (-not (Test-Slug $value) -or -not ($script:AllHarnesses -ccontains $value)) {
        return (Show-UsageError ("unknown harness '" + $value + "' (known: " + ($script:AllHarnesses -join ' ') + ')'))
      }
      if (-not ($script:WantH -ccontains $value)) { $script:WantH += $value }
    }
    elseif ($a -ceq '--plugin') {
      if (-not (Test-Slug $value) -or -not ($script:AllPlugins -ccontains $value)) {
        return (Show-UsageError ("unknown plugin '" + $value + "' (known: " + ($script:AllPlugins -join ' ') + ')'))
      }
      if (-not ($script:WantP -ccontains $value)) { $script:WantP += $value }
    }
    elseif ($a -ceq '--help' -or $a -ceq '-h') {
      Say $script:Usage
      return 0
    }
    else { return (Show-UsageError ('unknown option: ' + $a)) }
    $i++
  }

  if ($PSVersionTable.PSVersion.Major -lt 5) {
    Err 'install.ps1: needs Windows PowerShell 5.1 or later'
    return 1
  }
  try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
  } catch { }
  foreach ($p in $script:AllPlugins) {
    if ($script:WantP.Count -eq 0 -or $script:WantP -ccontains $p) {
      $script:Plugins += $p
      $script:Skills += $script:SkillsOf[$p]
    }
  }
  $how = $script:Mode
  if ($script:Dry) { $how = $script:Mode + ', dry run: nothing is changed' }
  Say ('LapisLazuli installer ' + $script:Version + ' (' + $how + ')')
  $os = 'Windows'
  if ($env:OS -ne 'Windows_NT') {
    try { $os = [Runtime.InteropServices.RuntimeInformation]::OSDescription } catch { $os = [string][Environment]::OSVersion }
  }
  Say ('  system: ' + $os + ', PowerShell ' + $PSVersionTable.PSVersion)
  if ($env:OS -eq 'Windows_NT') {
    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
      Say '  warning: running as administrator; this script needs no administrator rights'
    }
  } else {
    Say '  note: on macOS and Linux, install.sh is the supported script'
  }
  Say ('  source: https://github.com/' + $script:Repo + ' at ' + $script:Ref)
  Say ('  plugins: ' + ($script:Plugins -join ' '))
  $found = @()
  foreach ($h in $script:AllHarnesses) {
    Invoke-Harness $h 'name'
    Invoke-Harness $h 'detect'
    if (@($script:Why).Count -gt 0) {
      $found += $h
      if (Test-SkipExperimental $h) {
        Say ('  found: ' + $script:H + ' (' + ($script:Why -join ', ') + '); experimental, so not installed unless named: --harness ' + $h)
      } else {
        Say ('  found: ' + $script:H + ' (' + ($script:Why -join ', ') + ')')
      }
    }
  }
  $targets = @()
  if ($script:WantH.Count -gt 0) {
    $absent = $false
    foreach ($h in $script:AllHarnesses) {
      if (-not ($script:WantH -ccontains $h)) { continue }
      if ($found -ccontains $h) {
        $targets += $h
        continue
      }
      Invoke-Harness $h 'name'
      Invoke-Harness $h 'lookfor'
      Err ('install.ps1: ' + $script:H + ' is not installed here: found no ' + $script:Look + '.')
      Err ('  Install ' + $script:H + ' first, or leave out --harness ' + $h + '. Guide: ' + $script:Docs + $script:Anchor)
      $absent = $true
    }
    if ($absent) { return 1 }
  } else {
    $targets = @($found | Where-Object { -not (Test-SkipExperimental $_) })
  }
  if ($targets.Count -eq 0) {
    if ($found.Count -gt 0) { Say ('  no harness to install: the ones found are experimental; see ' + $script:Docs + '#identify-your-harness') }
    else { Say ('  no supported harness found; see ' + $script:Docs + '#identify-your-harness') }
  }

  if ($script:Mode -ne 'uninstall') {
    $script:Tool = Get-CliTool 'install'
    if (-not $script:Tool -and -not $script:Dry) {
      Err ('install.ps1: the CLI needs ' + $script:CliNeeds + ' on PATH; install one and run this again. Guide: ' + $script:Docs + '#cli-and-optional-components')
      return 1
    }
    Start-Phase $script:CliName @()
    if ($script:Tool) {
      Say ('  with: ' + $script:Tool)
      Invoke-CliSteps 'install' $script:Tool
    } else {
      Add-Failure ('CLI: no ' + $script:CliNeeds + ' on PATH')
    }
  }

  foreach ($h in $targets) { Invoke-Harness $h $script:Mode }

  if ($script:Mode -eq 'uninstall') {
    Start-Phase $script:CliName @()
    $tool = Get-CliTool 'uninstall'
    if ($script:WantH.Count -gt 0 -or -not (Test-AllPlugins)) {
      Say '  kept: the CLI goes only with every plugin from every harness'
    } elseif ($tool) {
      $script:Tool = $tool
      Invoke-CliSteps 'uninstall' $tool
    } else {
      Say ('  no ' + $script:CliNeeds + ' on PATH; remove the CLI with the tool that installed it')
    }
  } else {
    Start-Phase 'Check the CLI' @()
    Invoke-CliVerify
    foreach ($h in $targets) {
      Invoke-Harness $h 'name'
      Invoke-Harness $h 'verify'
    }
  }

  Write-Block '== Checks to run' $script:Checks '  '
  Write-Block '== To do by hand' $script:Todo '  '
  if ($script:Mode -ne 'uninstall') { Show-Snippets }
  Write-Block '== Notes' $script:Notes '  '
  Say ''
  Say '== Summary'
  if ($script:Dry) { Say '  dry run: nothing was changed' }
  elseif ($script:Changes.Count -gt 0) {
    Say '  changed:'
    foreach ($line in $script:Changes) { Say ('    ' + $line) }
  } else { Say '  nothing was changed' }
  if ($script:Failed.Count -gt 0) {
    Say '  failed:'
    foreach ($line in $script:Failed) { Say ('    ' + $line) }
    return 1
  }
  return 0
}

$code = @(Invoke-Main $args)[-1]
if (Get-Variable -Name PSCommandPath -ValueOnly -ErrorAction SilentlyContinue) { exit $code }
if ($code -ne 0) { Say ('install.ps1 finished with exit code ' + $code) }
$global:LASTEXITCODE = $code
